### ISSUE TITLE
Issue when building with gradle

### ISSUE THREAD

**Issue by Tobejizzle** [0x3C50/Renderer#15] opened 2022-09-21 21:48 UTC
When I try to build my gradle project with this repo i get this error : 

Could not find io.github.ladysnake:satin:1.9.0

any help is appreciated, 

thanks :)

**Comment by 0x3C50** [comment] 2022-10-15 12:23
Satin wasn't found, can you send the entire gradle log?

**Comment by Quinntonk** [comment] 2022-10-25 20:16
\--- com.github.0x3C50:Renderer:master-SNAPSHOT
     +--- net.fabricmc:fabric-loader:0.14.9
     +--- net.fabricmc.fabric-api:fabric-api-base:0.4.10+e62f51a390 -> 0.4.12+93d8cb8290
     +--- net.fabricmc.fabric-api:fabric-resource-loader-v0:0.6.0+6bee109e90 -> 0.7.2+70efcffe90
     \--- io.github.ladysnake:satin:1.9.0 FAILED

**Comment by 0x3C50** [comment] 2022-11-20 19:21
Totally forgot about this issue, did you get it to work? I tried to reproduce the issue a few days ago and it worked fine.

**Comment by Quinntonk** [comment] 2022-11-20 19:48
originally I was following your guide "How to make a modern fabric client" following the steps I was not able to get it to work but it might of been through my own ignorance of being fairly new to Java / Gradle. I ended up putting it in my repository manually rather than using Gradle because I kept getting that Satin error. Works great though!

**Comment by 0x3C50** [comment] 2022-11-20 20:00
Thanks!
I'm gonna close this for now, I'll look into why it fails later. It might be jfrog, but I'm not entirely sure

**Closed by 0x3C50** 2022-11-20 20:00 UTC

**Comment by Goby56** [comment] 2023-07-10 17:19
I'm trying to get the latest version using jitpack and gradle but I get a similar error to @Tobejizzle:
`io.github.ladysnake:satin:1.13.0`

I've tried getting the build directly from [jitpack](https://jitpack.io/#ladysnake/satin) but the same error persists.

The version before this works fine but I need the `ObjFile.ResourceProvider` from the latest version.

**Comment by 0x3C50** [comment] 2023-07-10 17:54
> I'm trying to get the latest version using jitpack and gradle but I get a similar error to @Tobejizzle: `Could not find io.github.ladysnake:satin:1.13.0`
> 
> I've tried getting the build directly from [jitpack](https://jitpack.io/#ladysnake/satin) but the same error persists.
> 
> The version before this works fine but I need the `ObjFile.ResourceProvider` from the latest version.

This is weird, the dependency resolves correctly on my end. Try to limit the jitpack repository to only accept the dependencies you directly use, the jitpack repo might wrongfully pick up on the `io.github.ladysnake` group.

**Comment by Goby56** [comment] 2023-07-10 18:24
I tried adding a `includeGroup` filter to the jitpack repository but I still get the same error
```gradle
repositories {
        maven {
              url 'https://jitpack.io'
              content { includeGroup "com.github.0x3C50" }
	}
}
```

This is how the dependency looks like btw:
`include modImplementation("com.github.0x3C50:Renderer:804df50")`

Here's the full error if it helps
```
A problem occurred configuring root project 'Hyper-Explosions'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find io.github.ladysnake:satin:1.13.0.
     Searched in the following locations:
       - file:/D:/Github/Hyper-Explosions/.gradle/loom-cache/remapped_mods/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
       - https://maven.fabricmc.net/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
       - https://libraries.minecraft.net/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
       - https://libraries.minecraft.net/io/github/ladysnake/satin/1.13.0/satin-1.13.0.jar
       - https://repo.maven.apache.org/maven2/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
       - file:/C:/Users/karlr/.gradle/caches/fabric-loom/1.13.0/satin.jar
       - file:/D:/Github/Hyper-Explosions/.gradle/loom-cache/1.13.0/satin.jar
       - https://maven.shedaniel.me/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
       - https://maven.terraformersmc.com/releases/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
       - https://api.modrinth.com/maven/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
       - https://maven.isxander.dev/releases/io/github/ladysnake/satin/1.13.0/satin-1.13.0.pom
     Required by:
         project : > com.github.0x3C50:Renderer:804df50

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by Quinntonk** [comment] 2023-07-10 18:34
It seems to just be version dependent I got tired of trying to fix it and just went with different commits that did work.

**Comment by Goby56** [comment] 2023-07-10 20:17
> It seems to not have added the repository, can you try adding the satin repository to your own build script manually? Instructions for that can be found on the satin github page.

I tried doing it manually and after following their instructions and realising they have switched maven group a couple of times, I got it working. 

It seems as though they switched maven group for builds after 1.20 which means my mod didn't grab the correct repo. In their instruction they specify that you should use `org.ladysnake` but for mods prior to 1.20 you should instead use `io.github.ladysnake`. I suppose the dependencies

**Comment by Goby56** [comment] 2023-07-10 20:35
Now I get another issue however. Because the latest version of Renderer is for 1.20, the fabric loader has now started complaining of incompatible mod sets. It wants both fabric-api for 1.20 and Renderer for 1.20.

**Comment by Quinntonk** [comment] 2023-07-10 20:55
> Now I get another issue however. Because the latest version of Renderer is for 1.20, the fabric loader has now started complaining of incompatible mod sets. It wants both fabric-api for 1.20 and Renderer for 1.20.

I would try using this. I pulled this from a previous 1.19.3 project that for some reason did not have the same satin issue for me.

`include modImplementation("com.github.0x3C50:Renderer:f450a9f")`

**Comment by Goby56** [comment] 2023-07-10 21:19
> Yes, that is actually because you're on the wrong minecraft version. Renderer only supports 1.20 right now due to pretty significant changes regarding apis it uses from 1.19.4 to 1.20. You can downport the library yourself, or use an older version for 1.19.4

The thing I really need is the `.obj` renderer. Am I allowed to just use that in my project given that I provide credit and a copy of the licence?

**Comment by 0x3C50** [comment] 2023-07-11 03:50
> > Yes, that is actually because you're on the wrong minecraft version. Renderer only supports 1.20 right now due to pretty significant changes regarding apis it uses from 1.19.4 to 1.20. You can downport the library yourself, or use an older version for 1.19.4
> 
> 
> 
> The thing I really need is the `.obj` renderer. Am I allowed to just use that in my project given that I provide credit and a copy of the licence?
> 
> 

Sure, but the obj renderer uses a lot of other internals from the library, you'd need to port those as well
